### ISSUE TITLE
Rebranding - What do we call ourselves

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/Captains-Task-List#139]
Civic Raleigh
Oak City Civic Collective

**Comment by jhibbets** [comment]
Open Raleigh Brigade

**Comment by ChrisTheDBA** [comment]
70% Open Raleigh Brigade 30% Open Raleigh Labs - I think both have good "talkability" Maybe the 501c3 could be NC Open Pass Labs. I just really want something to be "labs" :)
